/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package progetto;

import java.awt.*;

public class JFrame extends javax.swing.JFrame {
    
    PacMan pacMan;
    Fantasma fan1;
    ThreadMovimentoPacman tmp;
    ThreadMovimentoFantasma tmf1;
    Condivisa c;
    Mappa mappa;
    TextureManager txm;

    /**
     * Creates new form JFrame
     */
    public JFrame() {
        initComponents();

        // Creo gestore texture
        txm = new TextureManager();

        //Creo condivisa
        c = new Condivisa(txm);

        // Crea la mappa
        mappa = new Mappa(c);
        mappa.trovaCancelletto();
        mappa.crea();

        // Crea il fantasma1
        fan1 = new Fantasma(c, 4);
        // e il thread per il suo movimento
        tmf1 = new ThreadMovimentoFantasma(fan1, c);
        tmf1.start();

        // Crea il giocatore
        pacMan = new PacMan(c);
        // e il thread per il suo movimento
        tmp = new ThreadMovimentoPacman(pacMan, fan1, c);
        tmp.start();

        // Avvio il thread che aggiorna la pagina
        ThreadRepaint tp = new ThreadRepaint(this);
        tp.start();
        
        this.setBackground(Color.BLACK);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setSize(mappa.getLarghezza() + 100, mappa.getAltezza() + 100);
        this.setVisible(true);
        this.setMaximizedBounds(new Rectangle(0, 0, 1000, 1000));
        
    }
    
    @Override
    public void paintComponents(Graphics g) {
        super.paintComponents(g);
    }
    
    @Override
    public void paint(Graphics g) {
        Image image = createImage(this.getWidth(), this.getHeight());
        Graphics graphics = image.getGraphics();
        graphics.clearRect(0, 0, this.getWidth(), this.getHeight());
        
        for (Rectangle r : c.getMuraMappa()) {
            graphics.setColor(Color.blue);
            graphics.fillRect(r.x, r.y, r.width, r.height);
        }
        
        pacMan.draw(graphics);
        fan1.draw(graphics);
        
        g.drawImage(image, 0, 0, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased

    }//GEN-LAST:event_formKeyReleased

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        char tastoPremuto = evt.getKeyChar();
        if (tastoPremuto == 'r') {
            c.resetGame(pacMan, fan1);
        } else {
            System.out.println(tastoPremuto);
            pacMan.assegnaDirezione(tastoPremuto);
        }
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    
    /*
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame jf = new JFrame();
                jf.setResizable(false);
                jf.setVisible(true);
            }
        });
        
    }
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
